---
title: "Linear models"
output: github_document
---


```{r, include = F}
library(tidyverse)
library(httr)
library(purrr)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```



## Import data
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type)
```


## Fit a model
```{r}
#Trying to plot a line that goes through stars & price, by borough
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) + 
  geom_point()
```


Let's fit the model we care about
```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```


Let's look at the results
```{r, include = F}
fit

#You get a lot of info with summary()
summary(fit)
summary(fit)$coef
coef(fit)
fitted.values(fit)
residuals(fit)
```


Let's look at the result better ... THE BROOM PACKAGE

```{r}
broom::glance(fit)

broom::tidy(fit) %>% 
  select(-std.error, -statistic) %>% 
  mutate(
    term = str_replace(term, "borough", "Borough: ")
  ) %>% 
  knitr::kable(digits = 3)
```


## Be in control of factors

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    borough = fct_infreq(borough), 
    room_type = fct_infreq(room_type)
  )
```


Look at the plot again ... peep the re-ordering that took place

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) + 
  geom_point()
```



Refit the model with the reordered

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)

broom::tidy(fit)
#Manhattan is now my reference value

broom::glance(fit)
#the AIC & signma & r.squared have stayed the same, the only thing that changed is the reference level
```




